L = {} -- Polish Content Strings by meerfi

///////////////////// -- [[ ExoOps ]] --
-- Weapons
ws = "tacrp_eo_"
w = ws .. "93r"
-- L["wep." .. w .. ".name.full"] = "Beretta 93 Raffica"
-- L["wep." .. w .. ".name"] = "93R"
L["wep." .. w .. ".desc"] = "Premiumowy pistolet strzelający serią z niewielkim odrzutem i świetnym strzelaniem z biodra."
L["wep." .. w .. ".desc.quote"] = "\"Wiara, pociąg! Weź pociąg!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
-- L["wep." .. w .. ".credits"] = "Assets: Alliance of Valiant Arms \nOriginally made for CS 1.6 by GR_Lucia \nSounds: Vunsunta, Infinity Ward & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "acr"
-- L["wep." .. w .. ".name.full"] = "Bushmaster ACR"
-- L["wep." .. w .. ".name"] = "ACR"
L["wep." .. w .. ".desc"] = "Karabin cywilny oferowany jako zaawansowana alternatywa dla innych popularnych platform. Modułowy odbiornik pozwala na użycie różnych kalibrów."
L["wep." .. w .. ".desc.quote"] = "\"Zabicie smoka to największy zaszczyt.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Bushmaster Firearms LLC"
-- L["wep." .. w .. ".credits"] = "Model: End of Days \nTextures: IppE \nSounds: Strelok & XLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "ar70"
-- L["wep." .. w .. ".name.full"] = "Beretta SC-70/.223"
-- L["wep." .. w .. ".name"] = "SC-70"
L["wep." .. w .. ".desc"] = "Masywny karabin szturmowy z kontrolowalną szybkostrzelnością."
-- L["wep." .. w .. ".desc.quote"] = "\"Is life always this hard, or is it just when you're a kid?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
-- L["wep." .. w .. ".credits"] = "Model & Textures: DaveW \nSounds: Vunsunta, xLongWayHome & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "auga1"
-- L["wep." .. w .. ".name.full"] = "Steyr AUG A1"
-- L["wep." .. w .. ".name"] = "AUG A1"
L["wep." .. w .. ".desc"] = "Klasyczna wersja AUG z większym magazynkiem i trybem automatycznym. \nDostarczana z domyślnie 1.5-krotnym celownikiem."
-- L["wep." .. w .. ".desc.quote"] = "\"I want blood!\" \"And you'll have it.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Steyr Arms"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Silentassassin12 \nSound & Animations: Tactical Intervention"

w = ws .. "browninghp"
-- L["wep." .. w .. ".name.full"] = "Browning Hi-Power"
-- L["wep." .. w .. ".name"] = "Browning HP"
L["wep." .. w .. ".desc"] = "Starożytny pistolet o doskonałej ogólnej wydajności, ale niskiej szybkostrzelności."
L["wep." .. w .. ".desc.quote"] = "\"Co do cholery...?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Model: Silvio Dante \nTextures: WangChung \nSounds: Vunsunta, Strelok \nAnimations: Tactical Intervention"

w = ws .. "calico"
-- L["wep." .. w .. ".name.full"] = "Calico M950A"
-- L["wep." .. w .. ".name"] = "Calico"
L["wep." .. w .. ".desc"] = "Dziwnie wyglądający pistolet kosmiczny z ogromnym magazynkiem helikalnym. Przekształcony na pełne automatyczne."
-- L["wep." .. w .. ".desc.quote"] = "\"I've got more hostages than you've had hot dinners.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Calico Light Weapons Systems"
-- L["wep." .. w .. ".credits"] = "Assets: Alliance of Valiant Arms \nRail and foregrip from Warface \nSounds: A.V.A., Warface, speedonerd \nAnimations: Tactical Intervention"

w = ws .. "dual_satana"
-- L["wep." .. w .. ".name"] = "Dueling Demons"
L["wep." .. w .. ".desc"] = "Para spersonalizowanych rewolwerów. Świetna celność dla akimbo, ale wolno strzela i przeładowuje."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
-- L["wep." .. w .. ".credits"] = "Model: Soul_Slayer \nTextures: Kimono \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "f2000"
-- L["wep." .. w .. ".name.full"] = "FN F2000"
-- L["wep." .. w .. ".name"] = "F2000"
L["wep." .. w .. ".desc"] = "Futurystyczny karabin szturmowy bullpup o doskonałej ergonomii. \nDomyślnie wyposażony w lunetę 1,6x."
L["wep." .. w .. ".desc.quote"] = "\"Czy właśnie powiedziałeś, że muszę wygrać jeden dla Gippera?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Assets: DICE (Battlefield 3) \nScope model from CSO2 \nSounds: CSO2 & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "fal"
-- L["wep." .. w .. ".name.full"] = "FN FAL"
-- L["wep." .. w .. ".name"] = "FAL"
L["wep." .. w .. ".desc"] = "Weteran karabin bojowy o dużej sile ognia, ale z dużym odrzutem."
L["wep." .. w .. ".desc.quote"] = "Prawa ręka wolnego świata."
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Model: Pete3D \nTextures: Millenia \nSounds: New World Interactive & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "g36c"
-- L["wep." .. w .. ".name.full"] = "HK G36C"
-- L["wep." .. w .. ".name"] = "G36C"
L["wep." .. w .. ".desc"] = "Kompaktowa wersja karabinu G36, która wymienia skuteczny zasięg na zwiększoną szybkostrzelność i poprawioną obsługę."
L["wep." .. w .. ".desc.quote"] = "\"Jasne. Co to za imię, Soap?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: TheLama \nTextures: Thanez, FxDarkLoki \nSound & Animations: Tactical Intervention"

w = ws .. "hkcaws"
-- L["wep." .. w .. ".name"] = "HK CAWS"
L["wep." .. w .. ".desc"] = "Prototypowy strzelba bullpup o przyzwoitym zasięgu i pełnym ogniu automatycznym. \nWyposażony w stały celownik 1,5x."
L["wep." .. w .. ".desc.quote"] = "\"Koniec jazdy, mutancie.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Millenia \nPorted from Fallout: New Vegas by speedonerd \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "howa"
-- L["wep." .. w .. ".name.full"] = "Howa Type 64"
-- L["wep." .. w .. ".name"] = "Type 64"
L["wep." .. w .. ".desc"] = "Japoński karabin bojowy o kontrolowanej szybkostrzelności."
-- L["wep." .. w .. ".desc.quote"] = "\"Priest-21, this is Trevor. Clear to fire. Kill Wyvern.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Howa Machinery"
-- L["wep." .. w .. ".credits"] = "Assets: Michau, ported from Fallout: New Vegas by 8sianDude \nSounds: speedonerd \nAnimations: Tactical Intervention"

w = ws .. "hushpup"
-- L["wep." .. w .. ".name.full"] = "SW Mk 22 Mod 0"
-- L["wep." .. w .. ".name"] = "Mk 22"
L["wep." .. w .. ".desc"] = "Wintage pistolet sił specjalnych zaprojektowany do operacji tajnych."
L["wep." .. w .. ".desc.quote"] = "\"Rozpoczynanie operacji Snake Eater.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
-- L["wep." .. w .. ".credits"] = "Model: Stoke \nTextures: Dayofdfeat12, edited by speedonerd \nSounds: oneshotofficial & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "izzyfal"
-- L["wep." .. w .. ".name.full"] = "DSA SA58 Light-Barrel"
-- L["wep." .. w .. ".name"] = "FAL Izzy"
L["wep." .. w .. ".desc"] = "Cywilna wersja ikonicznego karabinu bojowego. Trochę ciężka, ale ma doskonałą moc zatrzymującą i zasięg."
-- L["wep." .. w .. ".trivia.manufacturer"] = "DS Arms"
-- L["wep." .. w .. ".credits"] = "Model: Pete3D \nTextures: Enron \nSounds: New World Interactive & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "jericho"
-- L["wep." .. w .. ".name.full"] = "Jericho 941"
-- L["wep." .. w .. ".name"] = "Jericho"
L["wep." .. w .. ".desc"] = "Solidny pistolet 9mm o dużej mobilności i wysokiej szybkostrzelności. \nReklamowany jako \"Baby Eagle\" ze względu na powierzchowne podobieństwo do Desert Eagle."
L["wep." .. w .. ".desc.quote"] = "\"Do zobaczenia, kosmiczny kowboju...\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Israel Military Industries"
-- L["wep." .. w .. ".credits"] = "Model: philibuster \nTextures: oyman \nSounds: xLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "l85"
-- L["wep." .. w .. ".name.full"] = "Enfield L85A2"
-- L["wep." .. w .. ".name"] = "L85A2"
L["wep." .. w .. ".desc"] = "Brytyjski karabin bullpup o średniej wydajności i wątpliwej niezawodności. Nie zdziw się, jeśli czasami się zacina. \nDomyślnie wyposażony w lunetę 3x."
-- L["wep." .. w .. ".desc.quote"] = "\"SA80. Good bit of British kit...\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Royal Ordnance"
-- L["wep." .. w .. ".credits"] = "Model & Texture: Milo, edited by speedonerd \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "m3"
-- L["wep." .. w .. ".name"] = "Benelli M3"
L["wep." .. w .. ".desc"] = "Półautomatyczna strzelba z dobrą kontrolą odrzutu i celnością."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Benelli Armi S.p.A."
-- L["wep." .. w .. ".credits"] = "Model & Textures: Kimono \nSounds: Cas., Tactical Intervention \nAnimations: Tactical Intervention"

w = ws .. "m29"
-- L["wep." .. w .. ".name.full"] = "SW Model 29 \"Satan\""
-- L["wep." .. w .. ".name"] = "M29"
L["wep." .. w .. ".desc"] = "Dostosowany rewolwer magnum z ciężkim spustem, ale doskonałą kontrolą odrzutu."
L["wep." .. w .. ".desc.quote"] = "\"Czujesz się szczęściarzem, łobuzie?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
-- L["wep." .. w .. ".credits"] = "Model: Soul_Slayer \nTextures: Kimono \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "m60"
-- L["wep." .. w .. ".name"] = "M60"
L["wep." .. w .. ".desc"] = "Ciężki karabin maszynowy o dużej sile rażenia, ale niskiej szybkostrzelności. Nazywany \"Świnią\" ze względu na swoją wagę."
L["wep." .. w .. ".desc.quote"] = "\"Żyj za nic, albo umrzyj za coś. Twój wybór.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "General Dynamics"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Millenia \nSounds: xLongWayHome, Lain & rzen1th \nAnimations: Tactical Intervention"

w = ws .. "m712"
-- L["wep." .. w .. ".name.full"] = "M712 Schnellfeuer"
-- L["wep." .. w .. ".name"] = "M712"
L["wep." .. w .. ".desc"] = "Zabytkowy pistolet maszynowy o dużej celności, ale słabej kontroli odrzutu. Skuteczny w krótkich seriach."
L["wep." .. w .. ".desc.quote"] = "Zamek może uderzyć cię w twarz."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Mauser"
-- L["wep." .. w .. ".credits"] = "Assets: Battlefield: Korea \nOriginally ported to CS 1.6 by GR_Lucia \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "m733"
-- L["wep." .. w .. ".name.full"] = "Colt Model 733"
-- L["wep." .. w .. ".name"] = "M733"
L["wep." .. w .. ".desc"] = "Karabinek o długości zbliżonej do subkarabinka AR-15, z szybką szybkostrzelnością. Stała rękojeść nośna ogranicza opcje optyki."
L["wep." .. w .. ".desc.quote"] = "\"Robię to, co potrafię najlepiej; zbieram punkty.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta & The End \nTextures: Acid Snake & JamesM \nSounds: Vunsunta & Teh Strelok \nAnimations: Tactical Intervention"

w = ws .. "masada"
-- L["wep." .. w .. ".name.full"] = "Magpul Masada"
-- L["wep." .. w .. ".name"] = "Masada"
L["wep." .. w .. ".desc"] = "Zaawansowany karabin z lekką konstrukcją z polimeru."
L["wep." .. w .. ".desc.quote"] = "\"Mógłbyś oczyścić świat z żelaza, a ja sprzedawałbym drewniane pałki.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Magpul Indutries"
-- L["wep." .. w .. ".credits"] = "Model: End of Days \nTextures: IppE \nSounds: Strelok & XLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "mcx"
-- L["wep." .. w .. ".name.full"] = "SIG MCX SPEAR"
-- L["wep." .. w .. ".name"] = "MCX SPEAR"
L["wep." .. w .. ".desc"] = "Karabin bojowy zaprojektowany do różnych ról piechoty. Specjalna amunicja ma dużą penetrację pancerza i utrzymuje obrażenia na dystansie."
L["wep." .. w .. ".desc.quote"] = "\"Bravo Six, idziemy w ciemność.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer Inc."
-- L["wep." .. w .. ".credits"] = "Model & Textures: Akinaro & Farengar \nSounds: Infinity Ward, speedonerd, XLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "megastar"
-- L["wep." .. w .. ".name.full"] = "Star Megastar"
-- L["wep." .. w .. ".name"] = "Megastar"
L["wep." .. w .. ".desc"] = "Duży pistolet o solidnej konstrukcji. Duża pojemność i siła ognia, ale ma intensywny odrzut."
L["wep." .. w .. ".desc.quote"] = "\"Chcesz się ze mną rozprawić?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Star Bonifacio Echeverria"
-- L["wep." .. w .. ".credits"] = "Model: General Tso \nTextures: the_tub \nSounds: oneshotofficial & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "mg42"
-- L["wep." .. w .. ".name"] = "MG 42"
L["wep." .. w .. ".desc"] = "Antyczny karabin maszynowy o niesamowicie szybkiej szybkostrzelności. Może przeciąć ludzi na pół jak piła łańcuchowa. \nNie zaleca się strzelania z ramienia."
-- L["wep." .. w .. ".desc.quote"] = "Every beast has its own story."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Großfuß AG"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Red Orchestra 2 \nSounds: Red Orechesta 2, rzen1th \nAnimations: Tactical Intervention"

w = ws .. "mp5k"
-- L["wep." .. w .. ".name.full"] = "HK MP5K"
-- L["wep." .. w .. ".name"] = "MP5K"
L["wep." .. w .. ".desc"] = "Kompaktowa wersja ikonicznego SMG. Dobrze zrównoważony, ale zamiast precyzji i kontroli swojego pełnowymiarowego odpowiednika oferuje lepszą obsługę."
L["wep." .. w .. ".desc.quote"] = "\"Broń. Dużo broni.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Thanez \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "mp5sd"
-- L["wep." .. w .. ".name.full"] = "HK MP5SD6"
-- L["wep." .. w .. ".name"] = "MP5SD6"
L["wep." .. w .. ".desc"] = "Wariant legendarnego SMG z wbudowanym tłumikiem. Zmniejszony zasięg, ale niski odrzut i brak widocznych smug."
L["wep." .. w .. ".desc.quote"] = "\"Broń wolna.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Geno & Mr. Brightside \nSounds: Lakedown, Teh Sterlok \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "mpx"
-- L["wep." .. w .. ".name.full"] = "SIG MPX"
-- L["wep." .. w .. ".name"] = "MPX"
L["wep." .. w .. ".desc"] = "Zaawansowany SMG ze stabilnym odrzutem i przedłużonym magazynkiem."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Assets: Contract Wars \nOriginally ported to CS 1.6 by GR_Lucia \nAnimation: Tactical Intervention"

w = ws .. "p7"
-- L["wep." .. w .. ".name.full"] = "HK P7"
-- L["wep." .. w .. ".name"] = "P7"
L["wep." .. w .. ".desc"] = "Kompaktowy pistolet o szybkiej obsłudze, ale słabym zasięgu."
L["wep." .. w .. ".desc.quote"] = "\"Kto powiedział, że jesteśmy terrorystami?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: Lama \nTextures: The_Tub \nSounds: Optical Snare & One Shot \nAnimations: Tactical Intervention"

w = ws .. "p99"
-- L["wep." .. w .. ".name.full"] = "Walther P99"
-- L["wep." .. w .. ".name"] = "P99"
L["wep." .. w .. ".desc"] = "Dobrze zbalansowany pistolet z szybkim tempem ognia."
L["wep." .. w .. ".desc.quote"] = "\"Ścigajcie ich i zabijajcie po kolei.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
-- L["wep." .. w .. ".credits"] = "Model: Afterburner \nTextures: NCFurious \nSounds: KingFriday, Vunsunta & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "p210"
-- L["wep." .. w .. ".name.full"] = "SIG P210"
-- L["wep." .. w .. ".name"] = "P210"
L["wep." .. w .. ".desc"] = "Elegancki powojenny pistolet z jednorzędowym magazynkiem i kurkowym mechanizmem spustowym."
-- L["wep." .. w .. ".desc.quote"] = "\"Do you suppose that I come to bring peace to the world?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer"
-- L["wep." .. w .. ".credits"] = "Model: Silvio Dante \nTextures: Twinke Masta \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "psg1"
-- L["wep." .. w .. ".name.full"] = "HK PSG-1"
-- L["wep." .. w .. ".name"] = "PSG-1"
L["wep." .. w .. ".desc"] = "Elegancki półautomatyczny karabin snajperski o niezrównanej precyzji i kontroli odrzutu, ale z niższym niż średnia zasięgiem. \nDomyślnie wyposażony w lunetę 8x."
L["wep." .. w .. ".desc.quote"] = "\"Urodziłem się na polu bitwy. Wychowałem się na polu bitwy.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta & fallschrimjager \nTextures: Twinke Masta \nSounds: Navaro, Vunsunta, FxDarkLoki \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "rhino20ds"
-- L["wep." .. w .. ".name.full"] = "Chiappa Rhino 20DS"
-- L["wep." .. w .. ".name"] = "Rhino 20DS"
L["wep." .. w .. ".desc"] = "Nowoczesny rewolwer z krótką lufą i sześciokątnym bębnem. Mały kaliber i nisko położona lufa sprawiają, że broń jest szybka i łatwa do użycia."
L["wep." .. w .. ".desc.quote"] = "[ PAMIĘTAJ O NASZEJ OBIETNICY ]"
-- L["wep." .. w .. ".trivia.manufacturer"] = "Chiappa Firearms"
-- L["wep." .. w .. ".credits"] = "Model & Textures: MirzaMiftahulFadillah, edited by 8Z \nSounds: Ghost597879, Tatwaffe, The Wastes Mod \nAnimations: Tactical Intervention"

w = ws .. "scarl"
-- L["wep." .. w .. ".name.full"] = "FN SCAR-L"
-- L["wep." .. w .. ".name"] = "SCAR-L"
L["wep." .. w .. ".desc"] = "Modularny, lekki karabin szturmowy o umiarkowanej szybkostrzelności."
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2"

w = ws .. "scout"
-- L["wep." .. w .. ".name"] = "Steyr Scout"
L["wep." .. w .. ".desc"] = "Lekki karabin zaprojektowany z myślą o przenośności i komforcie, a nie o bezpośredniej sile ognia. Ma wbudowany dwójnóg. \nWyposażony w celownik 6x."
-- L["wep." .. w .. ".desc.quote"] = "\"Headshot!\" \"Humiliation!\" "
-- L["wep." .. w .. ".trivia.manufacturer"] = "Steyr Mannlicher"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Thanez \nSounds: iFlip, Vunsunta, Unbreakable \nAnimations: Tactical Intervention"

w = ws .. "sg510"
-- L["wep." .. w .. ".name.full"] = "SIG SG 510-1"
-- L["wep." .. w .. ".name"] = "SG 510"
L["wep." .. w .. ".desc"] = "Zabytkowy karabin bojowy o doskonałych osiągach na daleki dystans. Odrzut jest ostry, ale stabilny."
-- L["wep." .. w .. ".desc.quote"] = "\"He had a lot of guts.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Assets: World of Guns: Disassembly \nSounds: Sledgehammer Games \nAnimations: Tactical Intervention"

w = ws .. "spas15"
-- L["wep." .. w .. ".name.full"] = "Franchi SPAS-15"
-- L["wep." .. w .. ".name"] = "SPAS-15"
L["wep." .. w .. ".desc"] = "Następca legendarnej strzelby z trybem podawania magazynkowego. Ciężka waga pozwala na przyzwoitą kontrolę w trybie półautomatycznym."
L["wep." .. w .. ".desc.quote"] = "\"Poczekamy. Poczekamy i zobaczymy, co odkryje.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Luigi Franchi S.p.A."
-- L["wep." .. w .. ".credits"] = "Assets: filosoma, ported from Fallout: New Vegas by Kindred Flame \nSounds: Navaro, SevenZero & Magmacow \nAnimations: Tactical Intervention & speedonerd"

w = ws .. "winchester"
-- L["wep." .. w .. ".name.full"] = "Winchester M1873"
-- L["wep." .. w .. ".name"] = "M1873"
L["wep." .. w .. ".desc"] = "Ikoniczny karabin kowbojski o konstrukcji, która przetrwała do dziś. Venerowany klasyk - ale nieodpowiedni na współczesne pola bitew."
L["wep." .. w .. ".desc.quote"] = "\"Broń, która zdobyła Zachód.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Winchester Repeating Arms"
-- L["wep." .. w .. ".credits"] = "Model: Enron \nTextures: !NC!Furious \nSounds: Vunsunta \nAnimations: speedonerd"

-- Attachments (exoops)
-- L["att.ammo_modular_65gren.name.full"] = "ACR 6.5mm Grendel Mod Kit"
-- L["att.ammo_modular_65gren.name"] = "Grendel"
-- L["att.ammo_modular_65gren.desc"] = "Modification to load ammo with improved ballistics."

-- L["att.ammo_modular_450bm.name.full"] = "ACR .450 Bushmaster Mod Kit"
-- L["att.ammo_modular_450bm.name"] = "Bushmaster"
-- L["att.ammo_modular_450bm.desc"] = "Modification to load low capacity, high power magnum rounds."

-- L["att.bolt_spas15_pump.name.full"] = "Franchi SPAS-15 Pump-Action"
-- L["att.bolt_spas15_pump.name"] = "Pump"
-- L["att.bolt_spas15_pump.desc"] = "Switch to pump-action operation, sacrificing fire-rate for improved control."

-- L["att.trigger_mk22_locked.name.full"] = "Mk 22 Slide Lock"
-- L["att.trigger_mk22_locked.name"] = "Slide Lock"
-- L["att.trigger_mk22_locked.desc"] = "Locks the slide in place when firing to further reduce noise."

-- L["att.optic_howa_scope.name.full"] = "Howa Type 64 2.2x DMR Scope"
-- L["att.optic_howa_scope.name"] = "Scope"
-- L["att.optic_howa_scope.desc"] = "Proprietary marksman scope for the Type 64."

-- L["att.optic_g36c_scope.name.full"] = "G36C Integrated Scope"
-- L["att.optic_g36c_scope.name"] = "Int. Scope"
-- L["att.optic_g36c_scope.desc"] = "Low power integrated scope and carry handle for the G36C."

-- L["att.ammo_scout_376.name.full"] = "Scout .376 Steyr Mod Kit"
-- L["att.ammo_scout_376.name"] = ".376 Steyr"
-- L["att.ammo_scout_376.desc"] = "Modification to load a unique high-power hunting cartridge."