L = {} -- Swedish Content Strings by Moka

///////////////////// -- [[ ExoOps ]] --
-- Weapons
ws = "tacrp_eo_"
w = ws .. "93r"
L["wep." .. w .. ".name.full"] = "Beretta 93 Raffica"
L["wep." .. w .. ".name"] = "93R"
L["wep." .. w .. ".desc"] = "Premium pistol med snabb, icke-springande salvoeld och bra prestanda från höften."
L["wep." .. w .. ".desc.quote"] = "\"Faith, tåget! Ta tåget!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
L["wep." .. w .. ".credits"] = "Tillgångar: Alliance of Valiant Arms \nEgentligen gjord till CS 1.6 av GR_Lucia \nLjud: Vunsunta, Infinity Ward & speedonerd \nAnimationer: Tactical Intervention"

w = ws .. "acr"
L["wep." .. w .. ".name.full"] = "Bushmaster ACR"
L["wep." .. w .. ".name"] = "ACR"
L["wep." .. w .. ".desc"] = "Civilgevär erbjuden som ett avancerat alternativ till andra populära plattformar. Välbalanserat och kan använda diverse moderna ammunitionstyper."
L["wep." .. w .. ".desc.quote"] = "\"To slay a dragon is the greatest of honors.\""
L["wep." .. w .. ".desc.quote"] = "\"Att slakta en drake är den största hedern.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Bushmaster Firearms LLC"
L["wep." .. w .. ".credits"] = "Modell: End of Days \nTexturer: IppE \nLjud: Strelok & XLongWayHome \nAnimationer: Tactical Intervention"

w = ws .. "ar70"
L["wep." .. w .. ".name.full"] = "Beretta SC-70/.223"
L["wep." .. w .. ".name"] = "SC-70"
L["wep." .. w .. ".desc"] = "Skrymmande automatkarbin med kontrollerbar eldhastighet."
L["wep." .. w .. ".desc.quote"] = "\"Är lite alltid såhär tufft eller bara när du är barn?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
L["wep." .. w .. ".credits"] = "Modell & Texturer: DaveW \nLjud: Vunsunta, xLongWayHome & speedonerd \nAnimationer: Tactical Intervention"

w = ws .. "auga1"
L["wep." .. w .. ".name.full"] = "Steyr AUG A1"
L["wep." .. w .. ".name"] = "AUG A1"
L["wep." .. w .. ".desc"] = "Klassisk AUG-version med ett större magasin och automateld.\nUtrustat med ett fast 1,5x sikte och reservsikten."
L["wep." .. w .. ".desc.quote"] = "\"Jag vill ha blod!\" \"Du kommer få det.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Steyr Arms"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta \nTexturer: Silentassassin12 \nSound & Animationer: Tactical Intervention"

w = ws .. "browninghp"
L["wep." .. w .. ".name.full"] = "Browning Hi-Power"
L["wep." .. w .. ".name"] = "Browning HP"
L["wep." .. w .. ".desc"] = "Antik pistol med bra generell prestanda men låg eldhastighet."
L["wep." .. w .. ".desc.quote"] = "\"Vad i helskotta...?\""
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".credits"] = "Modell: Silvio Dante \nTexturer: WangChung \nLjud: Vunsunta, Strelok \nAnimationer: Tactical Intervention"

w = ws .. "calico"
L["wep." .. w .. ".name.full"] = "Calico M950A"
L["wep." .. w .. ".name"] = "Calico"
L["wep." .. w .. ".desc"] = "Udda rymdliknande pistol med massivt spiralformat magasin."
L["wep." .. w .. ".desc.quote"] = "\"Jag har fler gisslan än du har varma middagar.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Calico Light Weapons Systems"
L["wep." .. w .. ".credits"] = "Tillgångar: Alliance of Valiant Arms \nSkena och framgrepp från Warface \nLjud: A.V.A., Warface, speedonerd \nAnimationer: Tactical Intervention"

w = ws .. "dual_satana"
L["wep." .. w .. ".name"] = "Dueling Demons"
L["wep." .. w .. ".desc"] = "Ett par anpassader revolvrar. Bra träffsäkerhet för akimbo-vapen men sölig eldhastighet och omladdning."
L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
L["wep." .. w .. ".credits"] = "Modell: Soul_Slayer \nTexturer: Kimono \nLjud: Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "f2000"
L["wep." .. w .. ".name.full"] = "FN F2000"
L["wep." .. w .. ".name"] = "F2000"
L["wep." .. w .. ".desc"] = "Bullpup-karbin med hög eldhastighet och rörlighet, men ostabil rekyl tack vare dess ovanlig ergonomi.\nUtrustat med ett 1,6x sikte som standard."
L["wep." .. w .. ".desc.quote"] = "\"Sade du att jag måste vinna detta för Gipper:n?\""
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".credits"] = "Tillgångar: DICE (Battlefield 3) \nSiktets modell från CSO2 \nLjud: CSO2 & Vunsunta \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "fal"
L["wep." .. w .. ".name.full"] = "FN FAL"
L["wep." .. w .. ".name"] = "FAL"
L["wep." .. w .. ".desc"] = "Gammaldags stridsgevär med bra täckande eldkraft men väldigt hög rekyl."
L["wep." .. w .. ".desc.quote"] = "Fria världens högra arm."
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".credits"] = "Modell: Pete3D \nTexturer: Millenia \nLjud: New World Interactive & speedonerd \nAnimationer: Tactical Intervention"

w = ws .. "g36c"
L["wep." .. w .. ".name.full"] = "HK G36C"
L["wep." .. w .. ".name"] = "G36C"
L["wep." .. w .. ".desc"] = "Kompakt karbinversion av G36:an som växlar effektiv räckvidd mot ökad eldhastighet och förbättrad hantering."
L["wep." .. w .. ".desc.quote"] = "\"Aja... vad fan för namn är \"Soap\"?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Modell: TheLama \nTexturer: Thanez, FxDarkLoki \nSound & Animationer: Tactical Intervention"

w = ws .. "hkcaws"
L["wep." .. w .. ".name"] = "HK CAWS"
L["wep." .. w .. ".desc"] = "Prototyp helautomatisk bullpup-hagelbössa med hög precision och penetrationsförmåga.\nUtrustat med ett fast 1,5x sikte."
L["wep." .. w .. ".desc.quote"] = "\"Vägen är slut, mutantjävel. Dags att dö.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Tillgångar: Millenia \nPortat från Fallout: New Vegas av speedonerd \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "howa"
L["wep." .. w .. ".name.full"] = "Howa Type 64"
L["wep." .. w .. ".name"] = "Type 64"
L["wep." .. w .. ".desc"] = "Japanskt stridsgevär som skjuter speciell patron med sänkt laddning. Betydande vikt men väldigt kontrollerbar."
L["wep." .. w .. ".desc.quote"] = "\"Priest-21, detta är Trebor. Klart att skjuta. Döda Wyvern.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Howa Machinery"
L["wep." .. w .. ".credits"] = "Tillgångar: Michau, portat från Fallout: New Vegas av 8sianDude \nLjud: speedonerd \nAnimationer: Tactical Intervention"

w = ws .. "hushpup"
L["wep." .. w .. ".name.full"] = "SW Mk 22 Mod 0"
L["wep." .. w .. ".name"] = "Mk 22"
L["wep." .. w .. ".desc"] = "Gammaldags pistol till specialstyrkor designad för tysta operationer."
L["wep." .. w .. ".desc.quote"] = "\"Påbörjar operation Snake Eater.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
L["wep." .. w .. ".credits"] = "Modell: Stoke \nTexturer: Dayofdfeat12, redigerad av speedonerd \nLjud: oneshotofficial & speedonerd \nAnimationer: Tactical Intervention"

w = ws .. "izzyfal"
L["wep." .. w .. ".name.full"] = "DSA SA58 Light-Barrel"
L["wep." .. w .. ".name"] = "FAL Izzy"
L["wep." .. w .. ".desc"] = "Civilversion av det ikoniska stridsgeväret. Lite tung, men har utmärkt stoppkraft och räckvidd."
L["wep." .. w .. ".trivia.manufacturer"] = "DS Arms"
L["wep." .. w .. ".credits"] = "Modell: Pete3D \nTexturer: Enron \nLjud: New World Interactive & speedonerd \nAnimationer: Tactical Intervention"

w = ws .. "jericho"
L["wep." .. w .. ".name.full"] = "Jericho 941"
L["wep." .. w .. ".name"] = "Jericho"
L["wep." .. w .. ".desc"] = "Kraftig 9 mm pistol med bra rörlighet och hög eldhastighet. Marknadsförd som \"Baby Eagle\" för dess ytlig likhet till Desert Eagle."
L["wep." .. w .. ".desc.quote"] = "\"Vi ses, rymd-cowboy...\""
L["wep." .. w .. ".trivia.manufacturer"] = "Israel Military Industries"
L["wep." .. w .. ".credits"] = "Modell: philibuster \nTexturer: oyman \nLjud: xLongWayHome \nAnimationer: Tactical Intervention"

w = ws .. "l85"
L["wep." .. w .. ".name.full"] = "Enfield L85A2"
L["wep." .. w .. ".name"] = "L85A2"
L["wep." .. w .. ".desc"] = "Brittiskt bullpup-gevär med måttlig prestanda och välkända pålitlighetsproblem.\nUtrustat med ett 3x sikte som standard."
L["wep." .. w .. ".desc.quote"] = "\"SA80. Perfekta delen av den brittiska armén...\""
L["wep." .. w .. ".trivia.manufacturer"] = "Royal Ordnance"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Milo, redigerad av speedonerd \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "m3"
L["wep." .. w .. ".name"] = "Benelli M3"
L["wep." .. w .. ".desc"] = "Halvautomatisk hagelbössa med bra rekylkontroll och träffsäkerhet."
L["wep." .. w .. ".trivia.manufacturer"] = "Benelli Armi S.p.A."
L["wep." .. w .. ".credits"] = "Modell & Texturer: Kimono \nLjud: Cas., Tactical Intervention \nAnimationer: Tactical Intervention"

w = ws .. "m29"
L["wep." .. w .. ".name.full"] = "SW Model 29 \"Satan\""
L["wep." .. w .. ".name"] = "M29"
L["wep." .. w .. ".desc"] = "Anpassad magnum-revolver med tung avtryckare men hög skada över distans."
L["wep." .. w .. ".desc.quote"] = "\"Känner du dig tursam, tuffing?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
L["wep." .. w .. ".credits"] = "Modell: Soul_Slayer \nTexturer: Kimono \nLjud: Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "m60"
L["wep." .. w .. ".name"] = "M60"
L["wep." .. w .. ".desc"] = "Tung kulspruta med intensiv stoppkraft men låg eldhastighet. Döpt till \"Grisen\" för dess betydande tyngd."
L["wep." .. w .. ".desc.quote"] = "\"Lev för inget eller dö för något. Du bestämmer.\""
L["wep." .. w .. ".trivia.manufacturer"] = "General Dynamics"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta \nTexturer: Millenia \nLjud: xLongWayHome, Lain & rzen1th \nAnimationer: Tactical Intervention"

w = ws .. "m712"
L["wep." .. w .. ".name.full"] = "M712 Schnellfeuer"
L["wep." .. w .. ".name"] = "M712"
L["wep." .. w .. ".desc"] = "Gammaldags automatpistol med bra träffsäkerhet men dålig rekylkontroll. Effektiv vid kort salvoeld."
L["wep." .. w .. ".desc.quote"] = "Slutstycket kanske träffar dig i nyllet."
L["wep." .. w .. ".trivia.manufacturer"] = "Mauser"
L["wep." .. w .. ".credits"] = "Tillgångar: Battlefield: Korea \nEgentligen portat till CS 1.6 av GR_Lucia \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "m733"
L["wep." .. w .. ".name.full"] = "Colt Model 733"
L["wep." .. w .. ".name"] = "M733"
L["wep." .. w .. ".desc"] = "AR-15 med underkarbin längd och hög men svår kontrollerbar eldhastighet. Fast bärhandtag begränsar sikte alternativ."
L["wep." .. w .. ".desc.quote"] = "\"Jag gör det jag gör bäst; rån.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta & The End \nTexturer: Acid Snake & JamesM \nLjud: Vunsunta & Teh Strelok \nAnimationer: Tactical Intervention"

w = ws .. "masada"
L["wep." .. w .. ".name.full"] = "Magpul Masada"
L["wep." .. w .. ".name"] = "Masada"
L["wep." .. w .. ".desc"] = "Modernt gevär med lätt polymer konstruktion."
L["wep." .. w .. ".desc.quote"] = "\"Du kan få tömma världen på järn så börjar jag sälja träklubbor.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Magpul Indutries"
L["wep." .. w .. ".credits"] = "Modell: End of Days \nTexturer: IppE \nLjud: Strelok & XLongWayHome \nAnimationer: Tactical Intervention"

w = ws .. "mcx"
L["wep." .. w .. ".name.full"] = "SIG MCX SPEAR"
L["wep." .. w .. ".name"] = "MCX SPEAR"
L["wep." .. w .. ".desc"] = "Stridsgevär designad för diverse infanteri roller. Speciell ammunition har hög penetrationsförmåga och behåller skadan över avstånd."
L["wep." .. w .. ".desc.quote"] = "\"Bravo Six, in i mörkret.\""
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer Inc."
L["wep." .. w .. ".credits"] = "Modell & Texturer: Akinaro & Farengar \nLjud: Infinity Ward, speedonerd, XLongWayHome \nAnimationer: Tactical Intervention"

w = ws .. "megastar"
L["wep." .. w .. ".name.full"] = "Star Megastar"
L["wep." .. w .. ".name"] = "Megastar"
L["wep." .. w .. ".desc"] = "Stor pistol med tuff konstruktion. Bra kapacitet och stoppkraft men har intensiv rekyl."
L["wep." .. w .. ".desc.quote"] = "\"Vill du mucka med mig?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Star Bonifacio Echeverria"
L["wep." .. w .. ".credits"] = "Modell: General Tso \nTexturer: the_tub \nLjud: oneshotofficial & speedonerd \nAnimationer: Tactical Intervention"

w = ws .. "mg42"
L["wep." .. w .. ".name"] = "MG 42"
L["wep." .. w .. ".desc"] = "Gammaldags kulspruta med en otroligt snabb eldhastighet.\nSkjutande från axeln rekommenderas ej."
L["wep." .. w .. ".desc.quote"] = "Varje best har dess egna historia."
L["wep." .. w .. ".trivia.manufacturer"] = "Großfuß AG"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Red Orchestra 2 \nLjud: Red Orechesta 2, rzen1th \nAnimationer: Tactical Intervention"

w = ws .. "mp5k"
L["wep." .. w .. ".name.full"] = "HK MP5K"
L["wep." .. w .. ".name"] = "MP5K"
L["wep." .. w .. ".desc"] = "Kompakt version av ikoniska kulsprutepistol. Välbalanserad, men den byter precision och kontrollen från dess helstora motsvarighet mot förbättrad hantering."
L["wep." .. w .. ".desc.quote"] = "\"Vapen. Många vapen.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta \nTexturer: Thanez \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "mp5sd"
L["wep." .. w .. ".name.full"] = "HK MP5SD6"
L["wep." .. w .. ".name"] = "MP5SD6"
L["wep." .. w .. ".desc"] = "En inbyggd ljuddämpad version av den ikoniska kulsprutepistolen. Sänkt räckvidd, men har låg rekyl och inget synligt spårljus."
L["wep." .. w .. ".desc.quote"] = "\"Fri eld.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta \nTexturer: Geno & Mr. Brightside \nLjud: Lakedown, Teh Sterlok \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "mpx"
L["wep." .. w .. ".name.full"] = "SIG MPX"
L["wep." .. w .. ".name"] = "MPX"
L["wep." .. w .. ".desc"] = "Avancerad kulsprutepistol med stabil rekyl och förlängt magasin."
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
L["wep." .. w .. ".credits"] = "Tillgångar: Contract Wars \nEgentligen portat till CS 1.6 av GR_Lucia \nAnimation: Tactical Intervention"

w = ws .. "p7"
L["wep." .. w .. ".name.full"] = "HK P7"
L["wep." .. w .. ".name"] = "P7"
L["wep." .. w .. ".desc"] = "Kompakt sidovapen med snabb hantering men dålig räckvidd."
L["wep." .. w .. ".desc.quote"] = "\"Vem sade att vi var terrorister?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Modell: Lama \nTexturer: The_Tub \nLjud: Optical Snare & One Shot \nAnimationer: Tactical Intervention"

w = ws .. "p99"
L["wep." .. w .. ".name.full"] = "Walther P99"
L["wep." .. w .. ".name"] = "P99"
L["wep." .. w .. ".desc"] = "Välbalanserad pistol med snabb eldhastighet."
L["wep." .. w .. ".desc.quote"] = "\"Jaga fram dem alla och döda dem, en efter en.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
L["wep." .. w .. ".credits"] = "Modell: Afterburner \nTexturer: NCFurious \nLjud: KingFriday, Vunsunta & speedonerd \nAnimationer: Tactical Intervention"

w = ws .. "p210"
L["wep." .. w .. ".name.full"] = "SIG P210"
L["wep." .. w .. ".name"] = "P210"
L["wep." .. w .. ".desc"] = "Elegant efterkrigs-, enkelstaplat, haneskjuten pistol.\nLite opålitlig tack vare dess ålder."
L["wep." .. w .. ".desc.quote"] = "\"Tror du att jag kommer få fred på denna värld?\""
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer"
L["wep." .. w .. ".credits"] = "Modell: Silvio Dante \nTexturer: Twinke Masta \nLjud: Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "psg1"
L["wep." .. w .. ".name.full"] = "HK PSG-1"
L["wep." .. w .. ".name"] = "PSG-1"
L["wep." .. w .. ".desc"] = "Elegant halvautomatiskt krypskyttegevär med ojämförlig precision och rekylkontroll. Utrustat med ett 8x kikarsikte som standard."
L["wep." .. w .. ".desc.quote"] = "\"Jag föddes på ett slagfält. Växte upp på ett slagfält.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta & fallschrimjager \nTexturer: Twinke Masta \nLjud: Navaro, Vunsunta, FxDarkLoki \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "rhino20ds"
L["wep." .. w .. ".name.full"] = "Chiappa Rhino 20DS"
L["wep." .. w .. ".name"] = "Rhino 20DS"
L["wep." .. w .. ".desc"] = "Modern \"snub-nose\"-revolver med hexagonal cylinder. Liten kaliber och \"low-bore\"-pipa gör vapnet snabbt och lätt att skjuta."
L["wep." .. w .. ".desc.quote"] = "[ KOM IHÅG DET VI LOVADE ]"
L["wep." .. w .. ".trivia.manufacturer"] = "Chiappa Firearms"
L["wep." .. w .. ".credits"] = "Modell & Texturer: MirzaMiftahulFadillah, redigerad av 8Z \nLjud: Ghost597879, Tatwaffe, The Wastes Mod \nAnimationer: Tactical Intervention"

w = ws .. "scarl"
L["wep." .. w .. ".name.full"] = "FN SCAR-L"
L["wep." .. w .. ".name"] = "SCAR-L"
L["wep." .. w .. ".desc"] = "Modulär och lätt automatkarbin med måttlig eldhastighet."
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".credits"] = "Tillgångar: Counter-Strike: Online 2"

w = ws .. "scout"
L["wep." .. w .. ".name"] = "Steyr Scout"
L["wep." .. w .. ".desc"] = "Lätt gevär designad för portabilitet och komfort istället för direkt stoppkraft. Har inbyggt skjutstöd.\nUtrustat med ett 6x kikarsikte som standard."
L["wep." .. w .. ".desc.quote"] = "\"Headshot!\" \"Humiliation!\" "
L["wep." .. w .. ".trivia.manufacturer"] = "Steyr Mannlicher"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta \nTexturer: Thanez \nLjud: iFlip, Vunsunta, Unbreakable \nAnimationer: Tactical Intervention"

w = ws .. "sg510"
L["wep." .. w .. ".name.full"] = "SIG SG 510-1"
L["wep." .. w .. ".name"] = "SG 510"
L["wep." .. w .. ".desc"] = "Gammaldags stridsgevär med utmärkt räckvidd och precision. Rekylen är stark men stabil, tack vare vapnets vikt."
L["wep." .. w .. ".desc.quote"] = "\"Han vågar väldigt mycket, han.\""
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
L["wep." .. w .. ".credits"] = "Tillgångar: World of Guns: Disassembly \nLjud: Sledgehammer Games \nAnimationer: Tactical Intervention"

w = ws .. "spas15"
L["wep." .. w .. ".name.full"] = "Franchi SPAS-15"
L["wep." .. w .. ".name"] = "SPAS-15"
L["wep." .. w .. ".desc"] = "Tung och magasinmatad efterträdare till den ikoniska dubbelläge hagelbössan. Låg rekyl men inte lika träffsäker."
L["wep." .. w .. ".desc.quote"] = "\"Vi får vänta. Väntar och se vad han kommer fram med.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Luigi Franchi S.p.A."
L["wep." .. w .. ".credits"] = "Tillgångar: filosoma, portad från Fallout: New Vegas av Kindred Flame \nLjud: Navaro, SevenZero & Magmacow \nAnimationer: Tactical Intervention & speedonerd"

w = ws .. "winchester"
L["wep." .. w .. ".name.full"] = "Winchester M1873"
L["wep." .. w .. ".name"] = "M1873"
L["wep." .. w .. ".desc"] = "Ikoniskt gevär som oftast kopplas till cowboys och fortfarande bland civila skytten. Rålig att skjuta, men är grundligt utklassad av moderna eldvapen."
L["wep." .. w .. ".desc.quote"] = "Vapnet som vann västern."
L["wep." .. w .. ".trivia.manufacturer"] = "Winchester Repeating Arms"
L["wep." .. w .. ".credits"] = "Modell: Enron \nTexturer: !NC!Furious \nLjud: Vunsunta \nAnimationer: speedonerd"

-- Attachments (exoops)
L["att.ammo_modular_65gren.name.full"] = "ACR 6,5 mm Grendel Modd Kit"
L["att.ammo_modular_65gren.name"] = "Grendel"
L["att.ammo_modular_65gren.desc"] = "Modifikation för att ladda patroner med ökad ballistik."

L["att.ammo_modular_450bm.name.full"] = "ACR .450 Bushmaster Modd Kit"
L["att.ammo_modular_450bm.name"] = "Bushmaster"
L["att.ammo_modular_450bm.desc"] = "Modifikation att ladda lägre kapacitet, högre kraft magnum-patroner."

L["att.bolt_spas15_pump.name.full"] = "Franchi SPAS-15 Pumprepeter"
L["att.bolt_spas15_pump.name"] = "Pumprepeter"
L["att.bolt_spas15_pump.desc"] = "Växla till pumprepeter hantering som offrar eldhastighet mot förbättrad kontroll."

L["att.trigger_mk22_locked.name.full"] = "Mk 22 Låst Slutstycke"
L["att.trigger_mk22_locked.name"] = "Låst Sluts."
L["att.trigger_mk22_locked.desc"] = "Lås slutstycket när du skjuter för att sänka ljudet."

L["att.optic_howa_scope.name.full"] = "Howa Type 64 2,2x DMR-Sikte"
L["att.optic_howa_scope.name"] = "Sikte"
L["att.optic_howa_scope.desc"] = "Proprietärt kikarsikte till Type 64:an."

L["att.optic_g36c_scope.name.full"] = "G36C Inbyggt Sikte"
L["att.optic_g36c_scope.name"] = "Inb. Sikte"
L["att.optic_g36c_scope.desc"] = "Inbyggt sikte med låg kraft och bärhandtag till G36C:n."

L["att.ammo_scout_376.name.full"] = "Scout .376 Steyr Modd Kit"
L["att.ammo_scout_376.name"] = ".376 Steyr"
L["att.ammo_scout_376.desc"] = "Modifikation för att ladda en unik jaktpatron med hög stoppkraft."