L = {} -- English Content Strings

///////////////////// -- [[ ExoOps ]] --
-- Weapons
ws = "tacrp_eo_"
w = ws .. "93r"
L["wep." .. w .. ".name.full"] = "Beretta 93 Raffica"
L["wep." .. w .. ".name"] = "93R"
L["wep." .. w .. ".desc"] = "Premium burst-fire pistol with a fast non-runaway burst and great hip-fire performance."
L["wep." .. w .. ".desc.quote"] = "\"Faith, the train! Take the train!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
L["wep." .. w .. ".credits"] = "Assets: Alliance of Valiant Arms \nOriginally made for CS 1.6 by GR_Lucia \nSounds: Vunsunta, Infinity Ward & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "acr"
L["wep." .. w .. ".name.full"] = "Bushmaster ACR"
L["wep." .. w .. ".name"] = "ACR"
L["wep." .. w .. ".desc"] = "Civilian rifle offered as an advanced alternative to other popular platforms. Well-rounded and can accept various modern ammo types."
L["wep." .. w .. ".desc.quote"] = "\"Ramirez! Defend the Burger Town!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Bushmaster Firearms LLC"
L["wep." .. w .. ".credits"] = "Model: End of Days \nTextures: IppE \nSounds: Strelok & XLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "ar70"
L["wep." .. w .. ".name.full"] = "Beretta SC-70/.223"
L["wep." .. w .. ".name"] = "SC-70"
L["wep." .. w .. ".desc"] = "Bulky assault rifle with a controllable rate of fire."
L["wep." .. w .. ".desc.quote"] = "\"Is life always this hard, or is it just when you're a kid?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
L["wep." .. w .. ".credits"] = "Model & Textures: DaveW \nSounds: Vunsunta, xLongWayHome & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "auga1"
L["wep." .. w .. ".name.full"] = "Steyr AUG A1"
L["wep." .. w .. ".name"] = "AUG A1"
L["wep." .. w .. ".desc"] = "Classic AUG variant with a larger magazine and full-auto.\nEquipped with a fixed 1.5x scope and backup ironsights."
L["wep." .. w .. ".desc.quote"] = "\"I want blood!\" \"And you'll have it.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Steyr Arms"
L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Silentassassin12 \nSound & Animations: Tactical Intervention"

w = ws .. "browninghp"
L["wep." .. w .. ".name.full"] = "Browning Hi-Power"
L["wep." .. w .. ".name"] = "Browning HP"
L["wep." .. w .. ".desc"] = "Antique pistol with great overall performance but low fire rate."
L["wep." .. w .. ".desc.quote"] = "\"What in the goddamn...?\""
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".credits"] = "Model: Silvio Dante \nTextures: WangChung \nSounds: Vunsunta, Strelok \nAnimations: Tactical Intervention"

w = ws .. "calico"
L["wep." .. w .. ".name.full"] = "Calico M950A"
L["wep." .. w .. ".name"] = "Calico"
L["wep." .. w .. ".desc"] = "Odd spacegun-looking pistol with a massive helical magazine."
L["wep." .. w .. ".desc.quote"] = "\"I've got more hostages than you've had hot dinners.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Calico Light Weapons Systems"
L["wep." .. w .. ".credits"] = "Assets: Alliance of Valiant Arms \nRail and foregrip from Warface \nSounds: A.V.A., Warface, speedonerd \nAnimations: Tactical Intervention"

w = ws .. "dual_satana"
L["wep." .. w .. ".name"] = "Dueling Demons"
L["wep." .. w .. ".desc"] = "Pair of customized revolvers. Great accuracy for akimbos but slow to fire and reload."
L["wep." .. w .. ".desc.quote"] = "\"I think your luck ran out, punk.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
L["wep." .. w .. ".credits"] = "Model: Soul_Slayer \nTextures: Kimono \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "f2000"
L["wep." .. w .. ".name.full"] = "FN F2000"
L["wep." .. w .. ".name"] = "F2000"
L["wep." .. w .. ".desc"] = "Bullpup carbine with high fire rate and mobility, but unstable recoil due to its unusual ergonomics.\nEquipped with a 1.6x scope by default."
L["wep." .. w .. ".desc.quote"] = "\"Did you just say I have to win one for the Gipper?\""
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".credits"] = "Assets: DICE (Battlefield 3) \nScope model from CSO2 \nSounds: CSO2 & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "fal"
L["wep." .. w .. ".name.full"] = "FN FAL"
L["wep." .. w .. ".name"] = "FAL"
L["wep." .. w .. ".desc"] = "Vintage battle rifle with great suppressing power but violent recoil."
L["wep." .. w .. ".desc.quote"] = "The right arm of the free world."
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".credits"] = "Model: Pete3D \nTextures: Millenia \nSounds: New World Interactive & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "g36c"
L["wep." .. w .. ".name.full"] = "HK G36C"
L["wep." .. w .. ".name"] = "G36C"
L["wep." .. w .. ".desc"] = "Compact carbine variant of the G36 that trades effective range for increased firerate and improved handling."
L["wep." .. w .. ".desc.quote"] = "\"Right... What the hell kind of name is \"Soap,\" eh?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Model: TheLama \nTextures: Thanez, FxDarkLoki \nSound & Animations: Tactical Intervention"

w = ws .. "hkcaws"
L["wep." .. w .. ".name"] = "HK CAWS"
L["wep." .. w .. ".desc"] = "Prototype automatic bullpup shotgun with high accuracy and high armor penetration.\nEquipped with a fixed 1.5x scope."
L["wep." .. w .. ".desc.quote"] = "\"Your ride's over, mutie. Time to die.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Assets: Millenia \nPorted from Fallout: New Vegas by speedonerd \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "howa"
L["wep." .. w .. ".name.full"] = "Howa Type 64"
L["wep." .. w .. ".name"] = "Type 64"
L["wep." .. w .. ".desc"] = "Japanese battle rifle firing a special reduced load cartridge. Considerable weight but highly controllable."
L["wep." .. w .. ".desc.quote"] = "\"Priest-21, this is Trebor. Clear to fire. Kill Wyvern.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Howa Machinery"
L["wep." .. w .. ".credits"] = "Assets: Michau, ported from Fallout: New Vegas by 8sianDude \nSounds: speedonerd \nAnimations: Tactical Intervention"

w = ws .. "hushpup"
L["wep." .. w .. ".name.full"] = "SW Mk 22 Mod 0"
L["wep." .. w .. ".name"] = "Mk 22"
L["wep." .. w .. ".desc"] = "Vintage special forces pistol designed for covert operations."
L["wep." .. w .. ".desc.quote"] = "\"Commencing operation Snake Eater.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
L["wep." .. w .. ".credits"] = "Model: Stoke \nTextures: Dayofdfeat12, edited by speedonerd \nSounds: oneshotofficial & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "izzyfal"
L["wep." .. w .. ".name.full"] = "DSA SA58 Light-Barrel"
L["wep." .. w .. ".name"] = "FAL Izzy"
L["wep." .. w .. ".desc"] = "Civilian variant of the iconic battle rifle. A bit heavy but boasts excellent stopping power and range."
L["wep." .. w .. ".desc.quote"] = "An American copy of a classic weapon."
L["wep." .. w .. ".trivia.manufacturer"] = "DS Arms"
L["wep." .. w .. ".credits"] = "Model: Pete3D \nTextures: Enron \nSounds: New World Interactive & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "jericho"
L["wep." .. w .. ".name.full"] = "Jericho 941"
L["wep." .. w .. ".name"] = "Jericho"
L["wep." .. w .. ".desc"] = "Sturdy 9mm pistol with great mobility and high firerate. \nMarketed as the \"Baby Eagle\" for its superficial resemblance to the Desert Eagle."
L["wep." .. w .. ".desc.quote"] = "\"See you, space cowboy...\""
L["wep." .. w .. ".trivia.manufacturer"] = "Israel Military Industries"
L["wep." .. w .. ".credits"] = "Model: philibuster \nTextures: oyman \nSounds: xLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "l85"
L["wep." .. w .. ".name.full"] = "Enfield L85A2"
L["wep." .. w .. ".name"] = "L85A2"
L["wep." .. w .. ".desc"] = "British bullpup rifle with middling performance and notorious reliability issues.\nEquipped with a 3x scope by default."
L["wep." .. w .. ".desc.quote"] = "\"SA80. Good bit of British kit...\""
L["wep." .. w .. ".trivia.manufacturer"] = "Royal Ordnance"
L["wep." .. w .. ".credits"] = "Model & Texture: Milo, edited by speedonerd \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "m3"
L["wep." .. w .. ".name"] = "Benelli M3"
L["wep." .. w .. ".desc"] = "Semi-automatic shotgun with good recoil control and accuracy."
L["wep." .. w .. ".desc.quote"] = "\"Come on, Daywalker!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Benelli Armi S.p.A."
L["wep." .. w .. ".credits"] = "Model & Textures: Kimono \nSounds: Cas., Tactical Intervention \nAnimations: Tactical Intervention"

w = ws .. "m29"
L["wep." .. w .. ".name.full"] = "SW Model 29 \"Satan\""
L["wep." .. w .. ".name"] = "M29"
L["wep." .. w .. ".desc"] = "Customized magnum revolver with a heavy trigger but great damage over distance."
L["wep." .. w .. ".desc.quote"] = "\"Do ya feel lucky, punk?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
L["wep." .. w .. ".credits"] = "Model: Soul_Slayer \nTextures: Kimono \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "m60"
L["wep." .. w .. ".name"] = "M60"
L["wep." .. w .. ".desc"] = "Heavy machine gun with intense stopping power but a low rate of fire. Nicknamed \"The Pig\" for its considerable heft."
L["wep." .. w .. ".desc.quote"] = "\"Live for nothing, or die for something. Your call.\""
L["wep." .. w .. ".trivia.manufacturer"] = "General Dynamics"
L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Millenia \nSounds: xLongWayHome, Lain & rzen1th \nAnimations: Tactical Intervention"

w = ws .. "m712"
L["wep." .. w .. ".name.full"] = "M712 Schnellfeuer"
L["wep." .. w .. ".name"] = "M712"
L["wep." .. w .. ".desc"] = "Antique machine pistol with great accuracy but poor recoil control. Effective in short bursts."
L["wep." .. w .. ".desc.quote"] = "The bolt might smack you in the face."
L["wep." .. w .. ".trivia.manufacturer"] = "Mauser"
L["wep." .. w .. ".credits"] = "Assets: Battlefield: Korea \nOriginally ported to CS 1.6 by GR_Lucia \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "m733"
L["wep." .. w .. ".name.full"] = "Colt Model 733"
L["wep." .. w .. ".name"] = "M733"
L["wep." .. w .. ".desc"] = "Sub-carbine-length AR-15 with a high but hard to control firerate. Fixed carry handle limits optic options."
L["wep." .. w .. ".desc.quote"] = "\"I do what I do best; I take scores.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
L["wep." .. w .. ".credits"] = "Model: Twinke Masta & The End \nTextures: Acid Snake & JamesM \nSounds: Vunsunta & Teh Strelok \nAnimations: Tactical Intervention"

w = ws .. "masada"
L["wep." .. w .. ".name.full"] = "Magpul Masada"
L["wep." .. w .. ".name"] = "Masada"
L["wep." .. w .. ".desc"] = "Modern rifle with lightweight polymer construction. Originally built for the U.S. military, it found more success as a civilian rifle."
L["wep." .. w .. ".desc.quote"] = "\"Break's over, Roach. Let's go.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Magpul Indutries"
L["wep." .. w .. ".credits"] = "Model: End of Days \nTextures: IppE \nSounds: Strelok & XLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "mcx"
L["wep." .. w .. ".name.full"] = "SIG MCX SPEAR"
L["wep." .. w .. ".name"] = "MCX SPEAR"
L["wep." .. w .. ".desc"] = "Battle rifle designed for multiple infantry roles. Specialized ammo has high armor penetration and maintains damage over range."
L["wep." .. w .. ".desc.quote"] = "\"Bravo Six, going dark.\""
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer Inc."
L["wep." .. w .. ".credits"] = "Model & Textures: Akinaro & Farengar \nSounds: Infinity Ward, speedonerd, XLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "megastar"
L["wep." .. w .. ".name.full"] = "Star Megastar"
L["wep." .. w .. ".name"] = "Megastar"
L["wep." .. w .. ".desc"] = "Large pistol with hefty construction. Great capacity and firepower but has intense recoil."
L["wep." .. w .. ".desc.quote"] = "\"You wanna fuck with me?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Star Bonifacio Echeverria"
L["wep." .. w .. ".credits"] = "Model: General Tso \nTextures: the_tub \nSounds: oneshotofficial & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "mg42"
L["wep." .. w .. ".name"] = "MG 42"
L["wep." .. w .. ".desc"] = "Antique machine gun with a blazing fast rate of fire.\nFiring from the shoulder is not recommended."
L["wep." .. w .. ".desc.quote"] = "Every beast has its own story."
L["wep." .. w .. ".trivia.manufacturer"] = "Großfuß AG"
L["wep." .. w .. ".credits"] = "Model & Textures: Red Orchestra 2 \nSounds: Red Orechesta 2, rzen1th \nAnimations: Tactical Intervention"

w = ws .. "mp5k"
L["wep." .. w .. ".name.full"] = "HK MP5K"
L["wep." .. w .. ".name"] = "MP5K"
L["wep." .. w .. ".desc"] = "Compact variant of the iconic SMG. Well-rounded but trades the precision and control of its full-size counterpart for improved handling."
L["wep." .. w .. ".desc.quote"] = "\"Guns. Lots of guns.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Thanez \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "mp5sd"
L["wep." .. w .. ".name.full"] = "HK MP5SD6"
L["wep." .. w .. ".name"] = "MP5SD6"
L["wep." .. w .. ".desc"] = "Intergrally suppressed variant of the iconic SMG. Reduced range, but has low recoil and no visible tracer."
L["wep." .. w .. ".desc.quote"] = "\"Weapons free.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Geno & Mr. Brightside \nSounds: Lakedown, Teh Sterlok \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "mpx"
L["wep." .. w .. ".name.full"] = "SIG MPX"
L["wep." .. w .. ".name"] = "MPX"
L["wep." .. w .. ".desc"] = "Advanced SMG with stable recoil and extended magazine."
L["wep." .. w .. ".desc.quote"] = "\"How the fuck can you make a shootout awkward?\""
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
L["wep." .. w .. ".credits"] = "Assets: Contract Wars \nOriginally ported to CS 1.6 by GR_Lucia \nAnimation: Tactical Intervention"

w = ws .. "p7"
L["wep." .. w .. ".name.full"] = "HK P7"
L["wep." .. w .. ".name"] = "P7"
L["wep." .. w .. ".desc"] = "Compact handgun with swift handling but poor range."
L["wep." .. w .. ".desc.quote"] = "\"Who said we were terrorists?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Model: Lama \nTextures: The_Tub \nSounds: Optical Snare & One Shot \nAnimations: Tactical Intervention"

w = ws .. "p99"
L["wep." .. w .. ".name.full"] = "Walther P99"
L["wep." .. w .. ".name"] = "P99"
L["wep." .. w .. ".desc"] = "Well-rounded pistol with a rapid rate of fire."
L["wep." .. w .. ".desc.quote"] = "\"Hunt them down and kill them off, one by one.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
L["wep." .. w .. ".credits"] = "Model: Afterburner \nTextures: NCFurious \nSounds: KingFriday, Vunsunta & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "p210"
L["wep." .. w .. ".name.full"] = "SIG P210"
L["wep." .. w .. ".name"] = "P210"
L["wep." .. w .. ".desc"] = "Sleek post-war, single-stack, hammer-fired pistol.\nSlightly unreliable due to its age."
L["wep." .. w .. ".desc.quote"] = "\"Do you suppose that I come to bring peace to the world?\""
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer"
L["wep." .. w .. ".credits"] = "Model: Silvio Dante \nTextures: Twinke Masta \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "psg1"
L["wep." .. w .. ".name.full"] = "HK PSG-1"
L["wep." .. w .. ".name"] = "PSG-1"
L["wep." .. w .. ".desc"] = "Elegant semi-automatic sniper with unmatched precision and recoil control. Equipped with an 8x scope by default."
L["wep." .. w .. ".desc.quote"] = "\"I was born on a battlefield. Raised on a battlefield.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Model: Twinke Masta & fallschrimjager \nTextures: Twinke Masta \nSounds: Navaro, Vunsunta, FxDarkLoki \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "rhino20ds"
L["wep." .. w .. ".name.full"] = "Chiappa Rhino 20DS"
L["wep." .. w .. ".name"] = "Rhino 20DS"
L["wep." .. w .. ".desc"] = "Modern snub-nose revolver with a hexagonal cylinder. Small caliber and low-bore barrel makes the gun quick and easy to fire."
L["wep." .. w .. ".desc.quote"] = "[ REMEMBER OUR PROMISE ]"
L["wep." .. w .. ".trivia.manufacturer"] = "Chiappa Firearms"
L["wep." .. w .. ".credits"] = "Model & Textures: MirzaMiftahulFadillah, edited by 8Z \nSounds: Ghost597879, Tatwaffe, The Wastes Mod \nAnimations: Tactical Intervention"

w = ws .. "scarl"
L["wep." .. w .. ".name.full"] = "FN SCAR-L"
L["wep." .. w .. ".name"] = "SCAR-L"
L["wep." .. w .. ".desc"] = "Modular, lightweight assault rifle with a moderate rate of fire."
L["wep." .. w .. ".desc.quote"] = "\"I've seen things, I've seen the way they are.\""
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2"

w = ws .. "scout"
L["wep." .. w .. ".name"] = "Steyr Scout"
L["wep." .. w .. ".desc"] = "Lightweight rifle designed for portability and comfort rather than direct firepower. Has a built-in bipod.\nEquipped with a 6x scope by default."
L["wep." .. w .. ".desc.quote"] = "\"Headshot!\" \"Humiliation!\" "
L["wep." .. w .. ".trivia.manufacturer"] = "Steyr Mannlicher"
L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Thanez \nSounds: iFlip, Vunsunta, Unbreakable \nAnimations: Tactical Intervention"

w = ws .. "sg510"
L["wep." .. w .. ".name.full"] = "SIG SG 510-1"
L["wep." .. w .. ".name"] = "SG 510"
L["wep." .. w .. ".desc"] = "Vintage battle rifle with excellent range and precision. Recoil is harsh but stable, thanks to the weapon's heft."
L["wep." .. w .. ".desc.quote"] = "\"He had a lot of guts.\""
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
L["wep." .. w .. ".credits"] = "Assets: World of Guns: Disassembly \nSounds: Sledgehammer Games \nAnimations: Tactical Intervention"

w = ws .. "spas15"
L["wep." .. w .. ".name.full"] = "Franchi SPAS-15"
L["wep." .. w .. ".name"] = "SPAS-15"
L["wep." .. w .. ".desc"] = "Heavy, magazine-fed successor to the iconic dual-mode shotgun. Low recoil but isn't very accurate."
L["wep." .. w .. ".desc.quote"] = "\"We will wait. We will wait and see what he can discover.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Luigi Franchi S.p.A."
L["wep." .. w .. ".credits"] = "Assets: filosoma, ported from Fallout: New Vegas by Kindred Flame \nSounds: DICE, SevenZero & Magmacow \nAnimation: Tactical Intervention, edited by speedonerd"

w = ws .. "winchester"
L["wep." .. w .. ".name.full"] = "Winchester M1873"
L["wep." .. w .. ".name"] = "M1873"
L["wep." .. w .. ".desc"] = "Iconic rifle synonymous with cowboys and still enjoyed among civilian shooters. Fun as it is to shoot, it's thoroughly outclassed by most modern firearms."
L["wep." .. w .. ".desc.quote"] = "The gun that won the West."
L["wep." .. w .. ".trivia.manufacturer"] = "Winchester Repeating Arms"
L["wep." .. w .. ".credits"] = "Model: Enron \nTextures: !NC!Furious \nSounds: Vunsunta \nAnimations: speedonerd"

-- Attachments (exoops)
L["att.ammo_modular_65gren.name.full"] = "ACR 6.5mm Grendel Mod Kit"
L["att.ammo_modular_65gren.name"] = "Grendel"
L["att.ammo_modular_65gren.desc"] = "Modification to load ammo with improved ballistics."

L["att.ammo_modular_450bm.name.full"] = "ACR .450 Bushmaster Mod Kit"
L["att.ammo_modular_450bm.name"] = "Bushmaster"
L["att.ammo_modular_450bm.desc"] = "Modification to load low capacity, high power magnum rounds."

L["att.bolt_spas15_pump.name.full"] = "Franchi SPAS-15 Pump-Action"
L["att.bolt_spas15_pump.name"] = "Pump"
L["att.bolt_spas15_pump.desc"] = "Switch to pump-action operation, sacrificing fire-rate for improved control."

L["att.trigger_mk22_locked.name.full"] = "Mk 22 Slide Lock"
L["att.trigger_mk22_locked.name"] = "Slide Lock"
L["att.trigger_mk22_locked.desc"] = "Locks the slide in place when firing to further reduce noise."

L["att.optic_howa_scope.name.full"] = "Howa Type 64 2.2x DMR Scope"
L["att.optic_howa_scope.name"] = "Scope"
L["att.optic_howa_scope.desc"] = "Proprietary marksman scope for the Type 64."

L["att.optic_g36c_scope.name.full"] = "G36C Integrated Scope"
L["att.optic_g36c_scope.name"] = "Int. Scope"
L["att.optic_g36c_scope.desc"] = "Low power integrated scope and carry handle for the G36C."

L["att.ammo_scout_376.name.full"] = "Scout .376 Steyr Mod Kit"
L["att.ammo_scout_376.name"] = ".376 Steyr"
L["att.ammo_scout_376.desc"] = "Modification to load a unique high-power hunting cartridge."